### ISSUE TITLE
Add option to not create any alsa ports for announced remote clients

### ISSUE THREAD

**Issue by Momomentum** [davidmoreno/rtpmidid#131]
I use rtpmidid to talk to the network, so for me I don't need manage remote clients. My application just connects to "Network" and clients connect to rtpmidid. It would be awesome to have an option to disable creating ports on remote client announce. I looked into the code and found that I could produce the desired effect by removing the `mdns_rtpmidid::setup_service_browser`. If this is the right place I would create a MR that passes an option into mdns_rtpmidid_t.
What do you think?

**Comment by Momomentum** [comment]
I created a pull request: https://github.com/davidmoreno/rtpmidid/pull/132
Please let me know if there is a more elegant way of doing this.

**Comment by davidmoreno** [comment]
Hi,

I like the idea. I gave it a go with similar ideas in the 131-do-not-import-everything branch.

Still missing the setting thought command line.

**Comment by davidmoreno** [comment]
Thank you very much by the way for the pull request, finally i did not use as i wanted to give other names, and add the regex part. But great job! Thanks for your time!

**Comment by Momomentum** [comment]
Hey. No worries. Your option seems to be the better one, as regex seems to encompass everything. I will give that a spin today.

**Comment by Momomentum** [comment]
Works like a charm!
