### ISSUE TITLE
rtpmidid doesn't create any ALSA devices

### ISSUE THREAD

**Issue by agraef** [davidmoreno/rtpmidid#133]
This is on Manjaro, running Pipewire and ALSA. The title says it all, rtpmidid just doesn't create any ALSA devices any more, which makes it useless.

Also tried the last revision that built correctly in CI, rev. cbd42c6eef76eb96cddfcbeb19ce186c947cf917. ALSA devices work correctly there.

Both versions segfault on exit, though. Will submit a separate ticket for that.

**Comment by davidmoreno** [comment]
Fixed in master!

It was a bug introduced with some refactoring of start up code.

Thanks for the report!

**Comment by agraef** [comment]
Works without a hitch now, many thanks!
