### ISSUE TITLE
will not connect to iphone rtp session

### ISSUE THREAD

**Issue by mrsstaceyseigle** [davidmoreno/rtpmidid#17]
Options do not work. it will not connect to iphone rtp session. You can not connect to mac or windows devices from terminal using raspberry pi.

**Comment by davidmoreno** [comment]
Right now it works the other way, connect from iPhone/iPad to rtpmidid.

When connecting from rtpmidid to the iPad I have access to, I receive a `NO` answer, which means either I have something configured wrong in my test iPad, or rtpmidid sends the wrong requests. But according to the protocol its the former.

**Comment by davidmoreno** [comment]
Hi, just checked and can connect ONCE from rtpmidid to iPad. After that it seems rtpmidid loss track of the announced mdns entry and can no connect straight away, and a rtpmidid restart is required.

I suspect that after some time there will be a reannouncement and it be available again.

**Comment by davidmoreno** [comment]
As a workaround, I just added a new rtpmidid-cli command: "update-mdns". This forces a mdns reannouncement, and this makes the iOS device to reappear. Quite probably it happens in many other situations.

I will try to fix it for good, no need for command, now tha tI know the problem.

I think this is the same problem as in #24

**Comment by davidmoreno** [comment]
I think it is fixed at commit 250162cf.

Can somebody check? If not in some days I will just close this issue.

**Comment by davidmoreno** [comment]
Closing as I think it is fixed. If I'm wrong anybody is welcome to reopen.
