### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by tripslip38** [davidmoreno/rtpmidid#19]
Unsure if it's just my installed version of C++ or what, but I get an error when running make:

`rtpmidid-master/src/control_socket.cpp: In member function ‘void rtpmidid::control_socket_t::data_ready(int)’:
rtpmidid-master/src/control_socket.cpp:97:11: error: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Werror=sign-compare]
   97 |     if (l >= sizeof(buf) - 1){
      |         ~~^~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
`

I'm on Solus 4.1. G++ 9.2.0. Docs say it should adhere to C++17 when passed the compiler flag, which you do have as -std=c++17.

Any ideas?

**Comment by swilwerth** [comment]
Same problem here. I solved adding an explicit cast to long unsigned int in that comparison and it builds.

Original code:
` if (l >= sizeof(buf) - 1) { .... } 
`

Modified code:
` if ( (long unsigned int) l >= sizeof( buf ) - 1 ) { .... } 
`

**Comment by davidmoreno** [comment]
I just commited to use "auto" on the recv. Let me know if it works.

**Comment by swilwerth** [comment]
Hmm, there are two warnings treated as errors now.

`rtpmidid/src/control_socket.cpp:103:11: error: comparison of integer expressions of different signedness: ‘long int’ and ‘long unsigned int’ [-Werror=sign-compare]
  103 |     if (l >= sizeof(buf) - 1){
      |         ~~^~~~~~~~~~~~~~~~~~
`
And

`rtpmidid/src/control_socket.cpp:202:25: error: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::__cxx11::basic_string<char> >::size_type’ {aka ‘long unsigned int’} [-Werror=sign-compare]
  202 |         for (auto i=1; i<command_split.size(); i++) {
      |                        ~^~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
`
I suggest to use size_t for size comparisons.
I can do a PR with my proposed fix if you want.

Thank you!

**Comment by swilwerth** [comment]
Here we go: https://github.com/davidmoreno/rtpmidid/pull/20

**Comment by davidmoreno** [comment]
Merged. Thanks!
