### ISSUE TITLE
rtpmidid: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by rtpmidid)

### ISSUE THREAD

**Issue by freddieventura** [davidmoreno/rtpmidid#35]
Hi there,

I don't know if you guys have tried your program in `Debian Buster` Stable repos , but is not working.

```
rtpmidid: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by rtpmidid)
```

That library is not available on Debian estable repositories I am afraid. Any work around?

https://stackoverflow.com/questions/44773296/libstdc-so-6-version-glibcxx-3-4-20-not-found#46613656

Thank you

**Comment by davidmoreno** [comment]
There is no deb for debian buster, only Ubuntu. For next release I will try to make them. I suggest you just recompile the packages, its a simple `make deb` (maybe `fakeroot make deb`).
