### ISSUE TITLE
Handle RTP Midi headers with journals.

### ISSUE THREAD

**Issue by gaycodegal** [davidmoreno/rtpmidid#41]
I'm trying to connect my ipad's midi output to my linux system, so I compiled https://github.com/petegoodliffe/PGMidi because it seemed like the best place to start. It does send the signals (I would presume it's sending note on followed by note off, but I can't say as it's in hex) over the network to `rtpmidid`, but I'm pretty sure it stops there as rtpmidid prints out `[2021-05-02T23:49:30Z] [rtppeer.cpp:402] This RTP MIDI header has journal. Not implemented yet. Ignoring.`. So I'm curious what it would take to support them? Difficulty level?

Midi bytes (hex) sent look like `[90, 2c, 7f]` *pause* followed by `[80,2c,00]`.

**Comment by davidmoreno** [comment]
There is a branch journal (https://github.com/davidmoreno/rtpmidid/tree/journal) with some support. But still not ready.

I leave this issue open to track the progress of that branch.

**Comment by davidmoreno** [comment]
Basic journal is already implemented, should work.
