### ISSUE TITLE
raspberryPI connecting to macOS : Try to access end of buffer exception

### ISSUE THREAD

**Issue by TheTechnobear** [davidmoreno/rtpmidid#5]
with a raspberryPI connecting to macOS, Im seeing "Try to access end of buffer " exceptions/errors, using GDB ive tracked it down to here:

````
Breakpoint 1, rtpmidid::parse_buffer_t::check_enought (this=0x7effe59c, nbytes=193) at /home/patch/projects/3rdparty/rtpmidid/src/./netutils.hpp:44
44	        throw exception("Try to access end of buffer at {}", (position - start) + nbytes);
(gdb) bt
#0  rtpmidid::parse_buffer_t::check_enought (this=0x7effe59c, nbytes=193) at /home/patch/projects/3rdparty/rtpmidid/src/./netutils.hpp:44
#1  0x00125424 in rtpmidid::parse_buffer_t::copy_from (this=0x7effe59c, from=..., chars=193) at /home/patch/projects/3rdparty/rtpmidid/src/./netutils.hpp:174
#2  0x00125250 in rtpmidid::read_label (buffer=..., label=...) at /home/patch/projects/3rdparty/rtpmidid/src/netutils.cpp:60
#3  0x00108d48 in read_answer (server=0x7effef80, buffer=...) at /home/patch/projects/3rdparty/rtpmidid/src/mdns.cpp:121
#4  0x0010a3e4 in parse_packet (mdns=0x7effef80, parse_buffer=...) at /home/patch/projects/3rdparty/rtpmidid/src/mdns.cpp:400
#5  0x0010a560 in rtpmidid::mdns::mdns_ready (this=0x7effef80) at /home/patch/projects/3rdparty/rtpmidid/src/mdns.cpp:445
````

If I get time, I'll try to investigate some more

**Comment by davidmoreno** [comment]
Can you check the avahi-dns branch?

I will try to apply the mdns-avahi branch to the master branch ASAP, as with the custom mdns resolver we avoid one dependency, but some things are not working 100% right.

**Comment by TheTechnobear** [comment]
ok, so im not getting this issue on he avahi branch

for reference this is what Ive done:
````
git checkout avahi-mdns
git cherry-pick a933c6c38b4401d4a191976df4a9e94b24de0a0e 
sudo apt-get install libavahi-client-dev
````
(basically install avahi client, and cherry pick the change i made for compiling on rPI)

there are some other issues... but i'll raise new issues for them

I guess if you plan to merge this branch to master, you can close this issue

is this avahi  branch good for changes?

**Comment by TheTechnobear** [comment]
the changes from avahi have fixed this issue - so can close
