### ISSUE TITLE
channel pressure not supported

### ISSUE THREAD

**Issue by TheTechnobear** [davidmoreno/rtpmidid#6]
avahi branch

warning ->  'This event type 12 is not managed yet'

aseq.cpp.

I'll have a look to see if this is easy to add, I need this as I'm trying to send MPE midi over the connection.

am i good to add this to the avahi branch?

**Comment by TheTechnobear** [comment]
k, looks easer than expected, just aseq.cpp missing SND_SEQ_EVENT_CHANPRESS, 
as rtpmidid.cpp alsamidi_to_midiprotocol() already has handling
will, add and then commit change 

(it'll be on avahi-mdns branch, as that's what im working/testing on)

**Comment by davidmoreno** [comment]
If you manage to add this functionality I guess it will be super easy to cherry pick the changes later on master.

**Comment by TheTechnobear** [comment]
turned out to be trivial change :)
