### ISSUE TITLE
avahi-mdns branch : connection issues/oddities

### ISSUE THREAD

**Issue by TheTechnobear** [davidmoreno/rtpmidid#7]
so I can get this branch to working, but Im seeing the oddities....
(perhaps user errors?)

````
patch@patchbox:~/projects/rtpmidid/build $ src/rtpmidid 
[2019-11-21T15:35:35Z] [main.cpp:46] Real Time Protocol Music Instrument Digital Interface Daemon - alpha 19.05
[2019-11-21T15:35:35Z] [main.cpp:47] (C) 2019 David Moreno Montero <dmoreno@coralbits.com>
[2019-11-21T15:35:35Z] [mdns_rtpmidi.cpp:85] watch_new 5 1
[2019-11-21T15:35:35Z] [rtpserver.cpp:84] Listening RTP MIDI connections at 0.0.0.0:5004, with name: 'patchbox'
[2019-11-21T15:35:35Z] [mdns_rtpmidi.cpp:276] (Browser) NEW: service 'bear' of type '_apple-midi._udp' in domain 'local'
[2019-11-21T15:35:35Z] [mdns_rtpmidi.cpp:290] (Browser) CACHE_EXHAUSTED
[2019-11-21T15:35:35Z] [mdns_rtpmidi.cpp:290] (Browser) ALL_FOR_NOW
[2019-11-21T15:35:36Z] [mdns_rtpmidi.cpp:229] Service 'bear' of type '_apple-midi._udp' in domain 'local'
[2019-11-21T15:35:36Z] [mdns_rtpmidi.cpp:248] 	bear.local:5004 (192.168.1.94)
	TXT=
	cookie is 0
	is_local: false
	our_own: false
	wide_area: false
	multicast: true
	cached: true
[2019-11-21T15:35:36Z] [rtpmidid.cpp:193] New alsa port: 1, connects to 192.168.1.94:5004 (bear)
[2019-11-21T15:35:36Z] [mdns_rtpmidi.cpp:58] Service '/Client15/EntryGroup1' successfully established
[2019-11-21T15:35:36Z] [mdns_rtpmidi.cpp:276] (Browser) NEW: service 'patchbox' of type '_apple-midi._udp' in domain 'local'
[2019-11-21T15:35:36Z] [mdns_rtpmidi.cpp:225] Received own announcement
````

aconnect shows:
`````
client 0: 'System' [type=kernel]
    0 'Timer           '
    1 'Announce        '
client 14: 'Midi Through' [type=kernel]
    0 'Midi Through Port-0'
client 20: 'pisound' [type=kernel,card=1]
    0 'pisound MIDI PS-3TG77SW'
client 128: 'rtpmidi patchbox' [type=user,pid=3779]
    0 'Network         '
    1 'mymac            '
client 129: 'MEC MIDI OUTPUT' [type=user,pid=3605]
    0 'MIDI OUT        '
````

so we already appear to have 2 available sessions (0,1) 
but if I connect to 0 with aconnect it will crash, and 0 appears to do nothing.
on the mac I see  no connection. (so its not auto connected) 
seems a few issues in this area ... but not sure what to expect, so probably need to give into these later as separate issues?!

------

ok, on the mac, I see 'patchbox' (my rPI) in directory, but it will not connect to it. 
( has a habit of hanging core midi as well :( )

--------


If I manually created an entry on the mac, using IP:5004, then I am able to successful connect to it (it takes a around 5-10secs to connect?) 
this create a new alsa session (called 3 'mymac             ') 
which I can connect to with connect, and this then receives midi and works 
yay! success

one small oddity, usually the mac will report latency here, but its not doing this with rtpmidid.

ok, then when I close it,  I get 
````
[2019-11-21T15:46:14Z] [rtpserver.cpp:172] Unknown peer, and not connect on control. Ignoring. Control port.
FF FF 42 59  00 00 00 02  00 00 00 00  00 47 97 76  

..BY .... .... .G.v 
````

so definitely its looking pretty good, just a few oddities 

however, Im not quite sure what state the avahi-mdns is in, perhaps when merged to master some might be resolved?

**Comment by davidmoreno** [comment]
Well.. at least it does something.

If you can manage to get a network capture I can try to check whats going on.. but if you can try to have a look it will be much easier if you have acess to the hardware.

When I have some time (maybe next week?) I will try to have a look with an old macbook I have laying around.

**Comment by TheTechnobear** [comment]
I think we have 3 things to consider:

A) what do the initial 2 alsa sessions represent? are they supposed to there?

or. should we only get a session once we form a connection?
(Ive a suspicion perhaps they are bogus, so thats why when you start trying to use them you get issues) 

B) not being able to use the broadcast session (i.e. having to manually connect) 
Id like to create up (A) first, since perhaps this is the cause of this.

C) disconnection error, 
ok, this seems clear cut enough... but Id have to dig in deeper to see what its trying to do 


overall, I do wonder if it's best to get this on to master first , and resolve there.
OR 
get this branch inline with master... so consider this the leading dev branch?

(just so we have all our ducks lined up ;) )

**Comment by davidmoreno** [comment]
I think we should consider the avahi branch the devel branch. Well, actually it's all devel, there is no release yet.

I think the avahi experiment was successful, and actually avahi is a much better idea than a custom mdns resolver, so I will just merge avahi into master, and we can continue developing there.

About the sessions (I guess you mean ports?) they are the discovered remote hosts, and you can use aconnect (or qjackctl) to connect any local sequencer device to the remote host. This is the way to connect from rtpmidid to a remote system.

If you do the reverse, connect from a remote system to rtpmidid, it will apear there too.

Finally to force connecting from local to a non discoverable system, just now can be done only at startup, but in the future some kind of management command is required (rtpmidid-cli?).

**Comment by TheTechnobear** [comment]
why do I have 2 then? (0 Network, 1 mymac)
as far as I know... the only have 1 rtp client on my network ...

Interestingly the 'long name' on the mac session is 'Network Session 1', so perhaps that is supposed to be what 0 Network is, but it being truncated?
(unfortunately the mac add 'Network' to session name, so I cannot change it to test this) 

still doesn't explain why 2....

also according to the mac, there is at time of start up no connective active.. 
(so perhaps the alsa session is being connected but its not being connected to the rtp session?) 

I guess I need to look at the code to see what its attempting to do , and then see whats missing ;)

**Comment by davidmoreno** [comment]
Merged.

The two connections is one to expose a sequencer, the second to connect it directly to the other side.

"Network" is a way to force export a specific device. Connect a seq port to "Network" and magically appears on the other systems to be connected to. On the other peer the exported name is something like "hostname/devicename".

**Comment by davidmoreno** [comment]
> When I have some time (maybe next week?) I will try to have a look with an old macbook I have laying around.

The macbook is completely dead. So I can no help to make it work on MacOS, sorry. Maye I can help with some network dumps, but little more.

**Comment by TheTechnobear** [comment]
what platform are you testing this on?
are you testing against windows using rtpmidi from Tobias Erichsen?

i can do some tests on windows too...
we can determine what are mac specific issues vs more general issues.

id need to work out have to get some network dumps

----
also I think we should close this issue now, since its a little generic, it be better if I raise specific topics - also now you have merged this to master, Ive moved to that.

**Comment by davidmoreno** [comment]
Agreed. When you encounter a specific oddity, just open a new issue with one oddity per issue.

I test with TouchDAW on Android, RTPMidi from Tobias Erichsen on wine and on desktop, and with my DeppMind12D, which have wifi rtpmidi.

If you know more apps to test with, I'm eager to add them to my arsenal. But no MacOS nor iOS here.

**Comment by davidmoreno** [comment]
I forgot to mention that I still have to test with McLaren Labs rtpmidi (https://mclarenlabs.com/rtpmidi/). But no time yet.

**Comment by TheTechnobear** [comment]
on the one you have tested, it be cool if you could raise tickets for known issues....

then I'll know if things are mac specific or not.

I think mac is a pretty important platform, given Apple have been implementing RTP natively for a long time now - so id hope its a pretty thorough implementation.

also.. Ive got an iConnectivity mioXM on its way, so I can test against that :)
