### ISSUE TITLE
rtpmidid creates >10GB of sysloglog entries in one minute

### ISSUE THREAD

**Issue by henning** [davidmoreno/rtpmidid#76]
I just bought a new device - an iConnectivity mioXM, which also hat rtpmidi capabilities.

So I just wanted to check how it behaves when simply plugged in to my Linux machine (for proper setup it requires a Mac or Windows, maybe also drivers). And things looked good, there where midi ports and stuff, on my mac I saw rtpm,idi stuff from the interface.

But a minute later I got informed that my disk is about to run full, and it turned out my syslog was bloated up to 11GB...

I found huge amounts of lines like this:

```
Sep  8 19:17:52 henning-ThinkPad-X1-Extreme-2nd rtpmidid[1765]: #033[0;31m[2021-09-08T17:17:52Z] [poller.cpp:200]#033[0m Catched exception at poller: Error reading from rtpp
eer mioXM C09-10:5022
```
In this second alone 241099 times - alltogether I can grep "poller.cpp" 63521662 in the file. 
I assume, but didn't verify in detail if they are all the same...

I haven't yet setup any midi routing, so a loop or something is unlikely, but I can and will check again. 
But even with a loop I am not sure if it's useful to log anything multiple hundred k times a second.

The rtpmidid version I am using is a self-built deb from commit 8ed604fe77f2a7cac42e69ce5d5fce24ca1c90cc
Let me know if there is any more information I can provide.

**Comment by henning** [comment]
OK, i checked with the heard of current master, and it's more or less the same, only the line number changed:

"Sep  8 22:58:55 henning-ThinkPad-X1-Extreme-2nd rtpmidid[444434]: [poller.cpp:278] Caught exception at poller: Error reading from rtppeer mioXM C09-03:5008"

Thats built from commit ID 640379571ee7cbccfaa06f860bf4c552d502c67f

**Comment by davidmoreno** [comment]
I just pushed a commit that will it make not to log indefinetly, bug somehow I think will not fix at all your bug. 

I think the problem may lay on the `recvfrom` not getting data as expected, and then busy looping there. 

Maybe it passes through the poller, so other things will keep working.

If rtpmidid does not work as expected, could you get a gdb backtrace at `rtpclient.cpp:283`  or `rtpserver.cpp:233` to get more hints on whats going on?
