### ISSUE TITLE
Getting "Unknown peer" on session disconnect

### ISSUE THREAD

**Issue by Brettles** [davidmoreno/rtpmidid#94]
When a remote client disconnects, I'm seeing the message "Unknown peer (IP address details), and not connect on control". The connection is torn down from the client side; but it lives forever in rtpmidid until it is terminated and restarted.

I think this is because at line 168 in `rtpserver.cpp` the initiator id is being taken from the third uint32; but in the BY message that is always zero.

I can repeat this behaviour using rtpMIDI for Windows and the built-in Mac MIDI utilities. The `test_rtpserver` test also fails.

Looking at the control message, it is the fourth uint32 that is common between the IN and BY control messages but I'm not familiar enough with MIDI (and MIDI in RTP) to say whether that's the right value to use when terminating the session. Certainly if I change line 168 from +8 to +12 it does not go well ;-) and I'm reluctant to make wholesale changes just to fix this one issue.

My environment is Ubuntu 20.04 - have not tested on any other distro.

**Comment by Brettles** [comment]
With a little more research, this looks like a regression introduced in https://github.com/davidmoreno/rtpmidid/commit/ad1511ed204c67a94d491ebf2cfab1e8465de441#diff-5b94509e06a46b55dd4c043da8604ce52ebc7ba6e616def3b082effeae68fd1c (apologies, I'm a Git n00b). Will create a pull request.

**Comment by Brettles** [comment]
Pull request: https://github.com/davidmoreno/rtpmidid/pull/95

**Comment by luzpaz** [comment]
Is this still relevant?

**Comment by Brettles** [comment]
Nope. It's fixed. Closing.
