### ISSUE TITLE
Unknow Issue Building from Source

### ISSUE THREAD

**Issue by enipklacus** [davidmoreno/rtpmidid#99]
Building from source gives a strange error: "/usr/include/fmt/core.h:1581:7: note: ‘formattable’ evaluates to false".
All dependencies are met. OS: Arch x64 running 6.4.12-arch1-1 kernel.
Any suggestions?

**Comment by davidmoreno** [comment]
Can you write here the full error? that looks deep inside some header, that I guess should not really fail. Also check if you can try with another libfmt version, maybe an older one?

**Comment by enipklacus** [comment]
Sorry for the waiting.
Here's the terminal output:

CMake Warning (dev) at CMakeLists.txt:1 (project):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


In file included from /usr/include/fmt/format.h:49,
                 from /usr/include/fmt/ostream.h:20,
                 from /home/lucas/rtpmidid/rtpmidid/lib/logger.cpp:20:
/usr/include/fmt/core.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; T = logger::Color; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/usr/include/fmt/core.h:1810:51:   required from ‘constexpr fmt::v10::format_arg_store<Context, Args>::format_arg_store(T& ...) [with T = {int, logger::Color, const std::basic_string_view<char, std::char_traits<char> >}; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; Args = {int, logger::Color, std::basic_string_view<char, std::char_traits<char> >}]’
/usr/include/fmt/core.h:1828:18:   required from ‘constexpr fmt::v10::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<T>::type>::type ...> fmt::v10::make_format_args(T& ...) [with Context = basic_format_context<appender, char>; T = {int, logger::Color, const std::basic_string_view<char, std::char_traits<char> >}]’
/usr/include/fmt/core.h:2790:44:   required from ‘std::string fmt::v10::format(format_string<T ...>, T&& ...) [with T = {int&, logger::Color&, const std::basic_string_view<char, std::char_traits<char> >&}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, int&, logger::Color&, const std::basic_string_view<char, std::char_traits<char> >&>]’
/home/lucas/rtpmidid/rtpmidid/lib/logger.cpp:43:21:   required from here
/usr/include/fmt/core.h:1577:63: error: ‘fmt::v10::detail::type_is_unformattable_for<logger::Color, char> _’ has incomplete type
 1577 |     type_is_unformattable_for<T, typename Context::char_type> _;
      |                                                               ^
/usr/include/fmt/core.h:1581:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1581 |       formattable,
      |       ^~~~~~~~~~~
/usr/include/fmt/core.h:1581:7: note: ‘formattable’ evaluates to false
make[3]: *** [lib/CMakeFiles/rtpmidid-shared.dir/build.make:132: lib/CMakeFiles/rtpmidid-shared.dir/logger.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /usr/include/fmt/format.h:49,
                 from /usr/include/fmt/ostream.h:20,
                 from /home/lucas/rtpmidid/rtpmidid/lib/logger.cpp:20:
/usr/include/fmt/core.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; T = logger::Color; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/usr/include/fmt/core.h:1810:51:   required from ‘constexpr fmt::v10::format_arg_store<Context, Args>::format_arg_store(T& ...) [with T = {int, logger::Color, const std::basic_string_view<char, std::char_traits<char> >}; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; Args = {int, logger::Color, std::basic_string_view<char, std::char_traits<char> >}]’
/usr/include/fmt/core.h:1828:18:   required from ‘constexpr fmt::v10::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<T>::type>::type ...> fmt::v10::make_format_args(T& ...) [with Context = basic_format_context<appender, char>; T = {int, logger::Color, const std::basic_string_view<char, std::char_traits<char> >}]’
/usr/include/fmt/core.h:2790:44:   required from ‘std::string fmt::v10::format(format_string<T ...>, T&& ...) [with T = {int&, logger::Color&, const std::basic_string_view<char, std::char_traits<char> >&}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, int&, logger::Color&, const std::basic_string_view<char, std::char_traits<char> >&>]’
/home/lucas/rtpmidid/rtpmidid/lib/logger.cpp:43:21:   required from here
/usr/include/fmt/core.h:1577:63: error: ‘fmt::v10::detail::type_is_unformattable_for<logger::Color, char> _’ has incomplete type
 1577 |     type_is_unformattable_for<T, typename Context::char_type> _;
      |                                                               ^
/usr/include/fmt/core.h:1581:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1581 |       formattable,
      |       ^~~~~~~~~~~
/usr/include/fmt/core.h:1581:7: note: ‘formattable’ evaluates to false
make[3]: *** [lib/CMakeFiles/rtpmidid-static.dir/build.make:132: lib/CMakeFiles/rtpmidid-static.dir/logger.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /usr/include/fmt/format.h:49,
                 from /home/lucas/rtpmidid/rtpmidid/include/rtpmidid/logger.hpp:21,
                 from /home/lucas/rtpmidid/rtpmidid/lib/mdns_rtpmidi.cpp:20:
/usr/include/fmt/core.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; T = AvahiWatchEvent; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/usr/include/fmt/core.h:1810:51:   required from ‘constexpr fmt::v10::format_arg_store<Context, Args>::format_arg_store(T& ...) [with T = {int, AvahiWatchEvent}; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; Args = {int, AvahiWatchEvent}]’
/usr/include/fmt/core.h:1828:18:   required from ‘constexpr fmt::v10::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<T>::type>::type ...> fmt::v10::make_format_args(T& ...) [with Context = basic_format_context<appender, char>; T = {int, AvahiWatchEvent}]’
/usr/include/fmt/core.h:2790:44:   required from ‘std::string fmt::v10::format(format_string<T ...>, T&& ...) [with T = {int&, AvahiWatchEvent&}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, int&, AvahiWatchEvent&>]’
/home/lucas/rtpmidid/rtpmidid/include/rtpmidid/logger.hpp:105:25:   required from ‘void logger::log(const char*, int, LogLevel, Args ...) [with Args = {const char*, int, AvahiWatchEvent}]’
/home/lucas/rtpmidid/rtpmidid/lib/mdns_rtpmidi.cpp:88:3:   required from here
/usr/include/fmt/core.h:1577:63: error: ‘fmt::v10::detail::type_is_unformattable_for<AvahiWatchEvent, char> _’ has incomplete type
 1577 |     type_is_unformattable_for<T, typename Context::char_type> _;
      |                                                               ^
/usr/include/fmt/core.h:1581:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1581 |       formattable,
      |       ^~~~~~~~~~~
/usr/include/fmt/core.h:1581:7: note: ‘formattable’ evaluates to false
In file included from /usr/include/fmt/format.h:49,
                 from /home/lucas/rtpmidid/rtpmidid/include/rtpmidid/exceptions.hpp:23,
                 from /home/lucas/rtpmidid/rtpmidid/lib/rtppeer.cpp:21:
/usr/include/fmt/core.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; T = rtpmidid::rtppeer::port_e; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/usr/include/fmt/core.h:1810:51:   required from ‘constexpr fmt::v10::format_arg_store<Context, Args>::format_arg_store(T& ...) [with T = {rtpmidid::rtppeer::port_e}; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; Args = {rtpmidid::rtppeer::port_e}]’
/usr/include/fmt/core.h:1828:18:   required from ‘constexpr fmt::v10::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<T>::type>::type ...> fmt::v10::make_format_args(T& ...) [with Context = basic_format_context<appender, char>; T = {rtpmidid::rtppeer::port_e}]’
/usr/include/fmt/core.h:2790:44:   required from ‘std::string fmt::v10::format(format_string<T ...>, T&& ...) [with T = {rtpmidid::rtppeer::port_e&}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, rtpmidid::rtppeer::port_e&>]’
/home/lucas/rtpmidid/rtpmidid/include/rtpmidid/logger.hpp:105:25:   required from ‘void logger::log(const char*, int, LogLevel, Args ...) [with Args = {const char*, rtpmidid::rtppeer::port_e}]’
/home/lucas/rtpmidid/rtpmidid/lib/rtppeer.cpp:164:5:   required from here
/usr/include/fmt/core.h:1577:63: error: ‘fmt::v10::detail::type_is_unformattable_for<rtpmidid::rtppeer::port_e, char> _’ has incomplete type
 1577 |     type_is_unformattable_for<T, typename Context::char_type> _;
      |                                                               ^
/usr/include/fmt/core.h:1581:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1581 |       formattable,
      |       ^~~~~~~~~~~
/usr/include/fmt/core.h:1581:7: note: ‘formattable’ evaluates to false
/usr/include/fmt/core.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; T = rtpmidid::rtppeer::status_e; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/usr/include/fmt/core.h:1810:51:   required from ‘constexpr fmt::v10::format_arg_store<Context, Args>::format_arg_store(T& ...) [with T = {rtpmidid::rtppeer::status_e, rtpmidid::rtppeer::port_e, bool}; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; Args = {rtpmidid::rtppeer::status_e, rtpmidid::rtppeer::port_e, bool}]’
/usr/include/fmt/core.h:1828:18:   required from ‘constexpr fmt::v10::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<T>::type>::type ...> fmt::v10::make_format_args(T& ...) [with Context = basic_format_context<appender, char>; T = {rtpmidid::rtppeer::status_e, rtpmidid::rtppeer::port_e, bool}]’
/usr/include/fmt/core.h:2790:44:   required from ‘std::string fmt::v10::format(format_string<T ...>, T&& ...) [with T = {rtpmidid::rtppeer::status_e&, rtpmidid::rtppeer::port_e&, bool&}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, rtpmidid::rtppeer::status_e&, rtpmidid::rtppeer::port_e&, bool&>]’
/home/lucas/rtpmidid/rtpmidid/include/rtpmidid/logger.hpp:105:25:   required from ‘void logger::log(const char*, int, LogLevel, Args ...) [with Args = {const char*, rtpmidid::rtppeer::status_e, rtpmidid::rtppeer::port_e, bool}]’
/home/lucas/rtpmidid/rtpmidid/lib/rtppeer.cpp:235:3:   required from here
/usr/include/fmt/core.h:1577:63: error: ‘fmt::v10::detail::type_is_unformattable_for<rtpmidid::rtppeer::status_e, char> _’ has incomplete type
 1577 |     type_is_unformattable_for<T, typename Context::char_type> _;
      |                                                               ^
/usr/include/fmt/core.h:1581:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1581 |       formattable,
      |       ^~~~~~~~~~~
/usr/include/fmt/core.h:1581:7: note: ‘formattable’ evaluates to false
/usr/include/fmt/core.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; T = AvahiBrowserEvent; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/usr/include/fmt/core.h:1810:51:   required from ‘constexpr fmt::v10::format_arg_store<Context, Args>::format_arg_store(T& ...) [with T = {AvahiBrowserEvent}; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; Args = {AvahiBrowserEvent}]’
/usr/include/fmt/core.h:1828:18:   required from ‘constexpr fmt::v10::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<T>::type>::type ...> fmt::v10::make_format_args(T& ...) [with Context = basic_format_context<appender, char>; T = {AvahiBrowserEvent}]’
/usr/include/fmt/core.h:2790:44:   required from ‘std::string fmt::v10::format(format_string<T ...>, T&& ...) [with T = {AvahiBrowserEvent&}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, AvahiBrowserEvent&>]’
/home/lucas/rtpmidid/rtpmidid/include/rtpmidid/logger.hpp:105:25:   required from ‘void logger::log(const char*, int, LogLevel, Args ...) [with Args = {const char*, AvahiBrowserEvent}]’
/home/lucas/rtpmidid/rtpmidid/lib/mdns_rtpmidi.cpp:305:5:   required from here
/usr/include/fmt/core.h:1577:63: error: ‘fmt::v10::detail::type_is_unformattable_for<AvahiBrowserEvent, char> _’ has incomplete type
 1577 |     type_is_unformattable_for<T, typename Context::char_type> _;
      |                                                               ^
/usr/include/fmt/core.h:1581:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1581 |       formattable,
      |       ^~~~~~~~~~~
/usr/include/fmt/core.h:1581:7: note: ‘formattable’ evaluates to false
make[3]: *** [lib/CMakeFiles/rtpmidid-static.dir/build.make:76: lib/CMakeFiles/rtpmidid-static.dir/rtppeer.cpp.o] Error 1
make[3]: *** [lib/CMakeFiles/rtpmidid-shared.dir/build.make:118: lib/CMakeFiles/rtpmidid-shared.dir/mdns_rtpmidi.cpp.o] Error 1
In file included from /usr/include/fmt/format.h:49,
                 from /home/lucas/rtpmidid/rtpmidid/include/rtpmidid/exceptions.hpp:23,
                 from /home/lucas/rtpmidid/rtpmidid/lib/rtppeer.cpp:21:
/usr/include/fmt/core.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; T = rtpmidid::rtppeer::port_e; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/usr/include/fmt/core.h:1810:51:   required from ‘constexpr fmt::v10::format_arg_store<Context, Args>::format_arg_store(T& ...) [with T = {rtpmidid::rtppeer::port_e}; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; Args = {rtpmidid::rtppeer::port_e}]’
/usr/include/fmt/core.h:1828:18:   required from ‘constexpr fmt::v10::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<T>::type>::type ...> fmt::v10::make_format_args(T& ...) [with Context = basic_format_context<appender, char>; T = {rtpmidid::rtppeer::port_e}]’
/usr/include/fmt/core.h:2790:44:   required from ‘std::string fmt::v10::format(format_string<T ...>, T&& ...) [with T = {rtpmidid::rtppeer::port_e&}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, rtpmidid::rtppeer::port_e&>]’
/home/lucas/rtpmidid/rtpmidid/include/rtpmidid/logger.hpp:105:25:   required from ‘void logger::log(const char*, int, LogLevel, Args ...) [with Args = {const char*, rtpmidid::rtppeer::port_e}]’
/home/lucas/rtpmidid/rtpmidid/lib/rtppeer.cpp:164:5:   required from here
/usr/include/fmt/core.h:1577:63: error: ‘fmt::v10::detail::type_is_unformattable_for<rtpmidid::rtppeer::port_e, char> _’ has incomplete type
 1577 |     type_is_unformattable_for<T, typename Context::char_type> _;
      |                                                               ^
/usr/include/fmt/core.h:1581:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1581 |       formattable,
      |       ^~~~~~~~~~~
/usr/include/fmt/core.h:1581:7: note: ‘formattable’ evaluates to false
/usr/include/fmt/core.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; T = rtpmidid::rtppeer::status_e; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/usr/include/fmt/core.h:1810:51:   required from ‘constexpr fmt::v10::format_arg_store<Context, Args>::format_arg_store(T& ...) [with T = {rtpmidid::rtppeer::status_e, rtpmidid::rtppeer::port_e, bool}; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; Args = {rtpmidid::rtppeer::status_e, rtpmidid::rtppeer::port_e, bool}]’
/usr/include/fmt/core.h:1828:18:   required from ‘constexpr fmt::v10::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<T>::type>::type ...> fmt::v10::make_format_args(T& ...) [with Context = basic_format_context<appender, char>; T = {rtpmidid::rtppeer::status_e, rtpmidid::rtppeer::port_e, bool}]’
/usr/include/fmt/core.h:2790:44:   required from ‘std::string fmt::v10::format(format_string<T ...>, T&& ...) [with T = {rtpmidid::rtppeer::status_e&, rtpmidid::rtppeer::port_e&, bool&}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, rtpmidid::rtppeer::status_e&, rtpmidid::rtppeer::port_e&, bool&>]’
/home/lucas/rtpmidid/rtpmidid/include/rtpmidid/logger.hpp:105:25:   required from ‘void logger::log(const char*, int, LogLevel, Args ...) [with Args = {const char*, rtpmidid::rtppeer::status_e, rtpmidid::rtppeer::port_e, bool}]’
/home/lucas/rtpmidid/rtpmidid/lib/rtppeer.cpp:235:3:   required from here
/usr/include/fmt/core.h:1577:63: error: ‘fmt::v10::detail::type_is_unformattable_for<rtpmidid::rtppeer::status_e, char> _’ has incomplete type
 1577 |     type_is_unformattable_for<T, typename Context::char_type> _;
      |                                                               ^
/usr/include/fmt/core.h:1581:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1581 |       formattable,
      |       ^~~~~~~~~~~
/usr/include/fmt/core.h:1581:7: note: ‘formattable’ evaluates to false
In file included from /usr/include/fmt/format.h:49,
                 from /home/lucas/rtpmidid/rtpmidid/include/rtpmidid/logger.hpp:21,
                 from /home/lucas/rtpmidid/rtpmidid/lib/mdns_rtpmidi.cpp:20:
/usr/include/fmt/core.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; T = AvahiWatchEvent; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/usr/include/fmt/core.h:1810:51:   required from ‘constexpr fmt::v10::format_arg_store<Context, Args>::format_arg_store(T& ...) [with T = {int, AvahiWatchEvent}; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; Args = {int, AvahiWatchEvent}]’
/usr/include/fmt/core.h:1828:18:   required from ‘constexpr fmt::v10::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<T>::type>::type ...> fmt::v10::make_format_args(T& ...) [with Context = basic_format_context<appender, char>; T = {int, AvahiWatchEvent}]’
/usr/include/fmt/core.h:2790:44:   required from ‘std::string fmt::v10::format(format_string<T ...>, T&& ...) [with T = {int&, AvahiWatchEvent&}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, int&, AvahiWatchEvent&>]’
/home/lucas/rtpmidid/rtpmidid/include/rtpmidid/logger.hpp:105:25:   required from ‘void logger::log(const char*, int, LogLevel, Args ...) [with Args = {const char*, int, AvahiWatchEvent}]’
/home/lucas/rtpmidid/rtpmidid/lib/mdns_rtpmidi.cpp:88:3:   required from here
/usr/include/fmt/core.h:1577:63: error: ‘fmt::v10::detail::type_is_unformattable_for<AvahiWatchEvent, char> _’ has incomplete type
 1577 |     type_is_unformattable_for<T, typename Context::char_type> _;
      |                                                               ^
/usr/include/fmt/core.h:1581:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1581 |       formattable,
      |       ^~~~~~~~~~~
/usr/include/fmt/core.h:1581:7: note: ‘formattable’ evaluates to false
/usr/include/fmt/core.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; T = AvahiBrowserEvent; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/usr/include/fmt/core.h:1810:51:   required from ‘constexpr fmt::v10::format_arg_store<Context, Args>::format_arg_store(T& ...) [with T = {AvahiBrowserEvent}; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; Args = {AvahiBrowserEvent}]’
/usr/include/fmt/core.h:1828:18:   required from ‘constexpr fmt::v10::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<T>::type>::type ...> fmt::v10::make_format_args(T& ...) [with Context = basic_format_context<appender, char>; T = {AvahiBrowserEvent}]’
/usr/include/fmt/core.h:2790:44:   required from ‘std::string fmt::v10::format(format_string<T ...>, T&& ...) [with T = {AvahiBrowserEvent&}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, AvahiBrowserEvent&>]’
/home/lucas/rtpmidid/rtpmidid/include/rtpmidid/logger.hpp:105:25:   required from ‘void logger::log(const char*, int, LogLevel, Args ...) [with Args = {const char*, AvahiBrowserEvent}]’
/home/lucas/rtpmidid/rtpmidid/lib/mdns_rtpmidi.cpp:305:5:   required from here
/usr/include/fmt/core.h:1577:63: error: ‘fmt::v10::detail::type_is_unformattable_for<AvahiBrowserEvent, char> _’ has incomplete type
 1577 |     type_is_unformattable_for<T, typename Context::char_type> _;
      |                                                               ^
/usr/include/fmt/core.h:1581:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1581 |       formattable,
      |       ^~~~~~~~~~~
/usr/include/fmt/core.h:1581:7: note: ‘formattable’ evaluates to false
make[3]: *** [lib/CMakeFiles/rtpmidid-shared.dir/build.make:76: lib/CMakeFiles/rtpmidid-shared.dir/rtppeer.cpp.o] Error 1
make[3]: *** [lib/CMakeFiles/rtpmidid-static.dir/build.make:118: lib/CMakeFiles/rtpmidid-static.dir/mdns_rtpmidi.cpp.o] Error 1
In file included from /usr/include/fmt/format.h:49,
                 from /home/lucas/rtpmidid/rtpmidid/include/rtpmidid/exceptions.hpp:23,
                 from /home/lucas/rtpmidid/rtpmidid/lib/rtpserver.cpp:26:
/usr/include/fmt/core.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; T = rtpmidid::rtppeer::port_e; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/usr/include/fmt/core.h:1810:51:   required from ‘constexpr fmt::v10::format_arg_store<Context, Args>::format_arg_store(T& ...) [with T = {char*, rtpmidid::rtppeer::port_e}; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; Args = {char*, rtpmidid::rtppeer::port_e}]’
/usr/include/fmt/core.h:1828:18:   required from ‘constexpr fmt::v10::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<T>::type>::type ...> fmt::v10::make_format_args(T& ...) [with Context = basic_format_context<appender, char>; T = {char*, rtpmidid::rtppeer::port_e}]’
/usr/include/fmt/core.h:2790:44:   required from ‘std::string fmt::v10::format(format_string<T ...>, T&& ...) [with T = {char*&, rtpmidid::rtppeer::port_e&}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, char*&, rtpmidid::rtppeer::port_e&>]’
/home/lucas/rtpmidid/rtpmidid/include/rtpmidid/logger.hpp:105:25:   required from ‘void logger::log(const char*, int, LogLevel, Args ...) [with Args = {const char*, char*, rtpmidid::rtppeer::port_e}]’
/home/lucas/rtpmidid/rtpmidid/lib/rtpserver.cpp:319:3:   required from here
/usr/include/fmt/core.h:1577:63: error: ‘fmt::v10::detail::type_is_unformattable_for<rtpmidid::rtppeer::port_e, char> _’ has incomplete type
 1577 |     type_is_unformattable_for<T, typename Context::char_type> _;
      |                                                               ^
/usr/include/fmt/core.h:1581:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1581 |       formattable,
      |       ^~~~~~~~~~~
/usr/include/fmt/core.h:1581:7: note: ‘formattable’ evaluates to false
In file included from /usr/include/fmt/format.h:49,
                 from /home/lucas/rtpmidid/rtpmidid/include/rtpmidid/exceptions.hpp:23,
                 from /home/lucas/rtpmidid/rtpmidid/lib/rtpserver.cpp:26:
/usr/include/fmt/core.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; T = rtpmidid::rtppeer::port_e; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/usr/include/fmt/core.h:1810:51:   required from ‘constexpr fmt::v10::format_arg_store<Context, Args>::format_arg_store(T& ...) [with T = {char*, rtpmidid::rtppeer::port_e}; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; Args = {char*, rtpmidid::rtppeer::port_e}]’
/usr/include/fmt/core.h:1828:18:   required from ‘constexpr fmt::v10::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<T>::type>::type ...> fmt::v10::make_format_args(T& ...) [with Context = basic_format_context<appender, char>; T = {char*, rtpmidid::rtppeer::port_e}]’
/usr/include/fmt/core.h:2790:44:   required from ‘std::string fmt::v10::format(format_string<T ...>, T&& ...) [with T = {char*&, rtpmidid::rtppeer::port_e&}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, char*&, rtpmidid::rtppeer::port_e&>]’
/home/lucas/rtpmidid/rtpmidid/include/rtpmidid/logger.hpp:105:25:   required from ‘void logger::log(const char*, int, LogLevel, Args ...) [with Args = {const char*, char*, rtpmidid::rtppeer::port_e}]’
/home/lucas/rtpmidid/rtpmidid/lib/rtpserver.cpp:319:3:   required from here
/usr/include/fmt/core.h:1577:63: error: ‘fmt::v10::detail::type_is_unformattable_for<rtpmidid::rtppeer::port_e, char> _’ has incomplete type
 1577 |     type_is_unformattable_for<T, typename Context::char_type> _;
      |                                                               ^
/usr/include/fmt/core.h:1581:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1581 |       formattable,
      |       ^~~~~~~~~~~
/usr/include/fmt/core.h:1581:7: note: ‘formattable’ evaluates to false
make[3]: *** [lib/CMakeFiles/rtpmidid-shared.dir/build.make:104: lib/CMakeFiles/rtpmidid-shared.dir/rtpserver.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:144: lib/CMakeFiles/rtpmidid-shared.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
make[3]: *** [lib/CMakeFiles/rtpmidid-static.dir/build.make:104: lib/CMakeFiles/rtpmidid-static.dir/rtpserver.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:170: lib/CMakeFiles/rtpmidid-static.dir/all] Error 2
make[1]: *** [Makefile:101: all] Error 2
make: *** [Makefile:30: build/bin/rtpmidid] Error 2

libfmt is installed. for all I know, all dependencies are satisfied.

**Comment by davidmoreno** [comment]
Ok, found it. There is a change in how libfmt manages enums, I think something on newer gcc, not sure. Anyway adding a lot of castings in many `DEBUG` that were debugging enum varaibles fixed the compilation. 

Just a lot of

```
-  return fmt::format("\033[{};{};{}m{}\033[0m", hl, color, bgcolor, str);
+  return fmt::format("\033[{};{};{}m{}\033[0m", hl, (int)color, (int)bgcolor, str);
```

I'm preparing a patch, will try to post it later today.

**Comment by davidmoreno** [comment]
Fixed at master.

Can you try it? If it works feel free to close this issue.

Thanks for the report.
